BioClientApi/Controllers/ClientController.cs
using BioClientApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Net;
using System.Text.Json;

namespace BioClientApi.Controllers
{
    public class clienteController : Controller
    {

        private List<ClientModel> clients;

        public IActionResult listar(string filtroNome, string filtroEmail, string filtroCPF)
        {

            string jsonFilePath = Path.Combine("Data", "clients.json");
            string jsonData = System.IO.File.ReadAllText(jsonFilePath);

            clients = JsonSerializer.Deserialize<List<ClientModel>>(jsonData);

            // Aplicar filtros
            if (!string.IsNullOrEmpty(filtroNome))
            {
                clients = clients.Where(c => c.Nome != null && c.Nome.Contains(filtroNome, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            if (!string.IsNullOrEmpty(filtroEmail))
            {
                clients = clients.Where(c => c.Email.Contains(filtroEmail, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            if (!string.IsNullOrEmpty(filtroCPF))
            {
                clients = clients.Where(c => c.CPF.Contains(filtroCPF, StringComparison.OrdinalIgnoreCase)).ToList();
            }


            return View(clients);
        }

        public IActionResult criar()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult criar(ClientModel newClient)
        {
            if (string.IsNullOrWhiteSpace(newClient.Email))
            {
                ModelState.AddModelError("Email", "O campo E-mail é obrigatório.");
            }

            if (string.IsNullOrWhiteSpace(newClient.CPF))
            {
                ModelState.AddModelError("CPF", "O campo CPF é obrigatório.");
            }

            if (string.IsNullOrWhiteSpace(newClient.RG))
            {
                ModelState.AddModelError("RG", "O campo RG é obrigatório.");
            }

            // Validar pelo menos um endereço com CEP
            if (newClient.Enderecos == null || !newClient.Enderecos.Any(e => !string.IsNullOrWhiteSpace(e.CEP)))
            {
                ModelState.AddModelError("Enderecos[0].CEP", "É necessário fornecer pelo menos um endereço com CEP.");
            }

            if (ModelState.IsValid)
            {
                // Novo ID
                int clientsLength = GetClientsLength();
                int newId = clientsLength + 1;

                // Atribui o novo ID ao cliente
                newClient.Id = newId;

                // Lê os clientes existentes do arquivo JSON
                string jsonFilePath = Path.Combine("Data", "clients.json");
                string jsonData = System.IO.File.ReadAllText(jsonFilePath);
                clients = JsonSerializer.Deserialize<List<ClientModel>>(jsonData);

                // Adiciona o novo cliente ao JSON
                clients.Add(newClient);
                string novoJsonData = JsonSerializer.Serialize(clients);
                System.IO.File.WriteAllText(jsonFilePath, novoJsonData);

                return Json(new { success = true });
            }
            else
            {
                var errors = ModelState.Keys
                .SelectMany(key => ModelState[key].Errors.Select(error => new { key, error.ErrorMessage }))
                .ToList();

                return Json(new { success = false, errors });
            }
        }

        public IActionResult atualizar(int id)
        {
            LoadClients();

            ClientModel client = clients.FirstOrDefault(c => c.Id == id);

            if (client == null)
            {
                return RedirectToAction("listar");
            }

            return View(client);
        }

        [HttpPost]
        public IActionResult atualizar(ClientModel client)
        {  
            LoadClients();

            var selectedClient = clients.FirstOrDefault(c => c.Id == client.Id);

            if (string.IsNullOrWhiteSpace(selectedClient.Email))
            {
                ModelState.AddModelError("Email", "O campo E-mail é obrigatório.");
            }

            if (string.IsNullOrWhiteSpace(selectedClient.CPF))
            {
                ModelState.AddModelError("CPF", "O campo CPF é obrigatório.");
            }

            if (string.IsNullOrWhiteSpace(selectedClient.RG))
            {
                ModelState.AddModelError("RG", "O campo RG é obrigatório.");
            }

            // Validar pelo menos um endereço com CEP
            if (selectedClient.Enderecos == null || !selectedClient.Enderecos.Any(e => !string.IsNullOrWhiteSpace(e.CEP)))
            {
                ModelState.AddModelError("Enderecos[0].CEP", "É necessário fornecer pelo menos um endereço com CEP.");
            }

            if (ModelState.IsValid && selectedClient != null)
            {
                // Atualizar Informacoes
                selectedClient.Nome = client.Nome;
                selectedClient.Email = client.Email;
                selectedClient.CPF = client.CPF;
                selectedClient.RG = client.RG;

                // Atualizar Contato
                UpdateContacts(client.Contatos, selectedClient.Contatos);

                // Atualizar Endereco
                UpdateAddresses(client.Enderecos, selectedClient.Enderecos);

                // Salvar no JSON
                string jsonFilePath = Path.Combine("Data", "clients.json");
                string novoJsonData = JsonSerializer.Serialize(clients);
                System.IO.File.WriteAllText(jsonFilePath, novoJsonData);

                return Json(new { success = true });
            }
            else
            {
                var errors = ModelState.Keys
                .SelectMany(key => ModelState[key].Errors.Select(error => new { key, error.ErrorMessage }))
                .ToList();

                return Json(new { success = false, errors });
            }
        }

        public IActionResult confirmarRemover(int id)
        {
            LoadClients();

            ClientModel client = clients.FirstOrDefault(c => c.Id == id);

            // Retornar se ID não existe
            if (client == null)
            {
                return RedirectToAction("listar");
            }

            return View(client);
        }

        public IActionResult remover(int id)
        {
            // Buscar o cliente pelo ID
            LoadClients();
            ClientModel client = clients.FirstOrDefault(c => c.Id == id);

            if (client != null)
            {
                // Remover o cliente da lista
                clients.Remove(client);

                // Atualizar o arquivo JSON
                string jsonFilePath = Path.Combine("Data", "clients.json");
                string novoJsonData = JsonSerializer.Serialize(clients);
                System.IO.File.WriteAllText(jsonFilePath, novoJsonData);
            }

            // Redirecionar de volta para a lista
            return RedirectToAction("listar");
        }

        private void LoadClients()
        {
            if (clients == null)
            {
                string jsonFilePath = Path.Combine("Data", "clients.json");
                string jsonData = System.IO.File.ReadAllText(jsonFilePath);
                clients = JsonSerializer.Deserialize<List<ClientModel>>(jsonData);
            }
        }

        private int GetClientsLength()
        {
            // Lê os clientes existentes do arquivo JSON
            string jsonFilePath = Path.Combine("Data", "clients.json");
            string jsonData = System.IO.File.ReadAllText(jsonFilePath);
            clients = JsonSerializer.Deserialize<List<ClientModel>>(jsonData);

            int clientsLength = clients.Count;

            return clientsLength;
        }

        private void UpdateContacts(List<ContactModel> sourceContacts, List<ContactModel> targetContacts)
        {
            foreach (var sourceContact in sourceContacts.ToList())
            {
                var targetContact = targetContacts.FirstOrDefault(c => c.Id == sourceContact.Id);

                if (targetContact != null)
                {
                    // Atualizar Contato
                    targetContact.Tipo = sourceContact.Tipo;
                    targetContact.DDD = sourceContact.DDD;
                    targetContact.Telefone = sourceContact.Telefone;
                }
                else
                {
                    // Adicionar Contato
                    targetContacts.Add(sourceContact);
                }
            }

            // Remover Contatos
            targetContacts.RemoveAll(tc => sourceContacts.All(sc => sc.Id != tc.Id));
        }

        private void UpdateAddresses(List<AddressModel> sourceAddresses, List<AddressModel> targetAddresses)
        {
            foreach (var sourceAddress in sourceAddresses)
            {
                var targetAddress = targetAddresses.FirstOrDefault(a => a.Id == sourceAddress.Id);

                if (targetAddress != null)
                {
                    // Atualizar Endereco
                    targetAddress.Tipo = sourceAddress.Tipo;
                    targetAddress.CEP = sourceAddress.CEP;
                    targetAddress.Logradouro = sourceAddress.Logradouro;
                    targetAddress.Numero = sourceAddress.Numero;
                    targetAddress.Bairro = sourceAddress.Bairro;
                    targetAddress.Complemento = sourceAddress.Complemento;
                    targetAddress.Cidade = sourceAddress.Cidade;
                    targetAddress.Estado = sourceAddress.Estado;
                    targetAddress.Referencia = sourceAddress.Referencia;
                }
                else
                {
                    // Adicionar Endereco
                    targetAddresses.Add(sourceAddress);
                }
            }

            // Remover Enderecos

BioClientApi/Views/cliente/atualizar.cshtml
@model ClientModel
@{
    ViewData["Title"] = "Atualizar cliente";
}

<div>
    <h1 class="display-5 mt-5 mb-5">Atualizar cliente</h1>
    <section>
        <form asp-action="Atualizar" method="post" id="updateUserForm" class="d-flex flex-wrap gap-5">
            <div class="form-group d-flex flex-column col-lg-5 border p-4 bg-light" style="max-width: 380px;">
                <h2 class="h4">Informações</h2>
                <input asp-for="Id" type="hidden" />
                <input asp-for="Nome" class="form-control my-2" placeholder="Nome" />
                <span asp-validation-for="Email" class="text-danger"></span>
                <input asp-for="Email" class="form-control my-2" placeholder="E-mail" />
                <span asp-validation-for="CPF" class="text-danger"></span>
                <input asp-for="CPF" id="cpfInput" class="form-control my-2" placeholder="CPF (somente números)" />
                <span asp-validation-for="RG" class="text-danger"></span>
                <input asp-for="RG" id="rgInput" class="form-control my-2" placeholder="RG (somente números)" />
            </div>

            <div class="form-group d-flex flex-column col-lg-3 border p-4 bg-light" style="max-width: 380px;">
                <h2 class="h4">Meios de contato</h2>
                <div id="contactNumbers">
                    
                    @for (int i = 0; i < Model.Contatos.Count; i++)
                    {
                        @if (i == 0)
                        {
                            <div id="contact-number-0">
                                <div class="row">
                                    <div class="col-12">
                                        <select asp-for="Contatos[i].Tipo" class="form-select my-2" aria-label="Selecionar...">
                                            <option value="Residencial">Residencial</option>
                                            <option value="Comercial">Comercial</option>
                                            <option value="Celular">Celular</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row mt-2 mb-2">
                                    <div class="col-3">
                                        <input asp-for="Contatos[i].DDD" type="text" class="form-control dddInput" placeholder="DDD" value="@Model.Contatos[i].DDD" />
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Contatos[i].Telefone" type="text" class="form-control phoneInput" placeholder="Número" value="@Model.Contatos[i].Telefone" />
                                    </div>
                                </div>
                            </div>
                        }

                        @if (i > 0)
                        {
                            <div id="contact-number-@i" class="mt-3 border-top pt-1">
                                <div class="row">
                                    <div class="col-10">
                                        <select asp-for="Contatos[i].Tipo" class="form-select my-2 col-5" aria-label="Selecionar...">
                                            <option value="Residencial">Residencial</option>
                                            <option value="Comercial">Comercial</option>
                                            <option value="Celular">Celular</option>
                                        </select>
                                    </div>
                                    <div class="col-2 p-0 d-flex align-items-center">
                                        <button type="button" onclick="removeContactNumber(@i)" class="btn btn-danger" style="width: 80%;">X</button>
                                    </div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-3">
                                        <input asp-for="Contatos[i].DDD" type="text" class="form-control dddInput" placeholder="DDD" value="@Model.Contatos[i].DDD" />
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="Contatos[i].Telefone" type="text" class="form-control phoneInput" placeholder="Número" value="@Model.Contatos[i].Telefone" />
                                    </div>
                                </div>
                            </div>
                        }

                    }


                </div>
                <button type="button" onclick="addContactNumber()" class="btn btn-primary mt-2">+ Novo número</button>
            </div>

            <div class="w-100 form-group border p-4 bg-light">
                <h2 class="h4 w-100">Endereços</h2>
                <div id="contactAddress">
                    @for (int i = 0; i < Model.Enderecos.Count; i++)
                    {
                        @if (i == 0)
                        {
                            <div id ="contact-address-0" class="d-flex flex-row flex-wrap gap-5">
                                <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                                    <select asp-for="Enderecos[i].Tipo" class="form-select m-2" aria-label="Selecionar...">
                                        <option value="Preferencial">Preferencial</option>
                                        <option value="Entrega">Entrega</option>
                                        <option value="Cobrança">Cobrança</option>
                                    </select>
                                    <input asp-for="Enderecos[i].Estado" class="form-control m-2" placeholder="Estado" value="@Model.Enderecos[i].Estado" />
                                    <span asp-validation-for="Enderecos[0].CEP" class="text-danger"></span>
                                    <input asp-for="Enderecos[i].CEP" class="form-control cepInputs m-2" placeholder="CEP" value="@Model.Enderecos[i].CEP" />
                                    <input asp-for="Enderecos[i].Cidade" class="form-control m-2" placeholder="Cidade" value="@Model.Enderecos[i].Cidade" />
                                </div>
                                <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                                    <input asp-for="Enderecos[i].Bairro" class="form-control m-2" placeholder="Bairro" value="@Model.Enderecos[i].Bairro" />
                                    <input asp-for="Enderecos[i].Logradouro" class="form-control m-2" placeholder="Rua" value="@Model.Enderecos[i].Logradouro" />
                                    <input asp-for="Enderecos[i].Numero" type="text" class="form-control numberAddressInput m-2" placeholder="Número" value="@Model.Enderecos[i].Numero" />
                                    <input asp-for="Enderecos[i].Complemento" class="form-control m-2" placeholder="Complemento" value="@Model.Enderecos[i].Complemento" />
                                </div>
                                <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                                    <textarea asp-for="Enderecos[i].Referencia" class="form-control m-2" placeholder="Referência">@Model.Enderecos[i].Referencia</textarea>
                                </div>
                            </div>
                        }
                        
                        @if (i > 0)
                        {
                            <div id="contact-address-@i" class="d-flex flex-row flex-wrap justify-content-center gap-5 mt-3 border-top pt-3">
                                <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                                    <select asp-for="Enderecos[i].Tipo" class="form-select m-2" aria-label="Selecionar...">
                                        <option value="Preferencial">Preferencial</option>
                                        <option value="Entrega">Entreag</option>
                                        <option value="Cobrança">Cobrança</option>
                                    </select>
                                    <input asp-for="Enderecos[i].Estado" class="form-control m-2" placeholder="Estado" value="@Model.Enderecos[i].Estado" />
                                    <input asp-for="Enderecos[i].CEP" class="form-control cepInputs m-2" placeholder="CEP" value="@Model.Enderecos[i].CEP" />
                                    <input asp-for="Enderecos[i].Cidade" class="form-control m-2" placeholder="Cidade" value="@Model.Enderecos[i].Cidade" />
                                </div>
                                <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                                    <input asp-for="Enderecos[i].Bairro" class="form-control m-2" placeholder="Bairro" value="@Model.Enderecos[i].Bairro" />
                                    <input asp-for="Enderecos[i].Logradouro" class="form-control m-2" placeholder="Rua" value="@Model.Enderecos[i].Logradouro" />
                                    <input asp-for="Enderecos[i].Numero" type="text" class="form-control numberAddressInput m-2" placeholder="Número" value="@Model.Enderecos[i].Numero" />
                                    <input asp-for="Enderecos[i].Complemento" class="form-control m-2" placeholder="Complemento" value="@Model.Enderecos[i].Complemento" />
                                </div>
                                <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                                    <textarea asp-for="Enderecos[i].Referencia" class="form-control m-2" placeholder="Referencia">@Model.Enderecos[i].Referencia</textarea>
                                    <div class="w-100 p-0 d-flex align-items-center mt-1">
                                        <button type="button" onclick="removeContactAddress(@i)" class="btn btn-danger mt-1">Remover endereço</button>
                                    </div>
                                </div>
                            </div>
                        }

                    }
                </div>
                <button type="button" onclick="addContactAddress()" class="btn btn-primary mt-3">+ Novo Endereço</button>
            </div>

            <div class="w-100 mb-5">
                <a role="button" class="btn btn-secondary m-1" asp-controller="cliente" asp-action="listar">Cancelar</a>
                <button type="submit" class="btn btn-primary m-1" asp-action="Atualizar">Atualizar cliente</button>
            </div>
        </form>
    </section>
</div>

BioClientApi/Views/cliente/confirmarRemover.cshtml
@model ClientModel
@{
    ViewData["Title"] = "Confirmar remoção de cliente";
}

<div class="text-center m-5">
    <h3>Confirmar remoção de cliente</h3>
</div>

<div class="container d-flex justify-content-center">
    <table class="table table-bordered" style="max-width: 450px;">
        <thead>
            <tr>
                <th colspan="2" class="text-center">Você tem certeza que deseja remover o cliente abaixo?</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>ID</th>
                <td>@Model.Id</td>
            </tr>
            <tr>
                <th>Nome</th>
                <td>@Model.Nome</td>
            </tr>
            <tr>
                <th>CPF</th>
                <td>@FormatarCPF(Model.CPF)</td>
            </tr>
            <tr>
                <th>RG</th>
                <td>@FormatarRG(Model.RG)</td>
            </tr>
        </tbody>
    </table>
</div>


<div class="d-flex justify-content-center">
    <a role="button" class="btn btn-secondary m-2" asp-controller="cliente" asp-action="listar">Voltar sem remover</a>
    <a role="button" class="btn btn-danger m-2" asp-controller="cliente" asp-action="remover" asp-route-id="@Model.Id">Remover cliente</a>
</div>

@functions {
    // Formatar CPF
    private string FormatarCPF(string cpf)
    {
        if (cpf.Length == 11)
        {
            return $"{cpf.Substring(0, 3)}.{cpf.Substring(3, 3)}.{cpf.Substring(6, 3)}-{cpf.Substring(9)}";
        }

        return cpf;
    }

    // Formatar RG
    private string FormatarRG(string rg)
    {
        if (!string.IsNullOrEmpty(rg) && rg.Length >= 9)
        {
            return $"{rg.Substring(0, 2)}.{rg.Substring(2, 3)}.{rg.Substring(5, 3)}-{rg.Substring(8)}";
        }

        return rg;
    }
}

BioClientApi/Views/cliente/criar.cshtml
@model ClientModel
@{
    ViewData["Title"] = "Criar um novo cliente";
}

<div>
    <h1 class="display-5 my-5">Criar um novo cliente</h1>
    <section>
        <form asp-action="criar" method="post" id="createNewUserForm" class="d-flex flex-wrap gap-5">
            <div class="form-group d-flex flex-column col-lg-5 border p-4 bg-light" style="max-width: 380px;">
                <h2 class="h4">Informações</h2>
                <input asp-for="Nome" class="form-control my-2" placeholder="Nome" />
                <span asp-validation-for="Email" class="text-danger"></span>
                <input asp-for="Email" class="form-control my-2" placeholder="E-mail (obrigátório)" />
                <span asp-validation-for="CPF" class="text-danger"></span>
                <input asp-for="CPF" id="cpfInput" class="form-control my-2" placeholder="CPF (obrigátório)" />
                <span asp-validation-for="RG" class="text-danger"></span>
                <input asp-for="RG" id="rgInput" class="form-control my-2" placeholder="RG (obrigátório)" />
            </div>

            <div class="form-group d-flex flex-column col-lg-3 border p-4 bg-light" style="max-width: 380px;">
                <h2 class="h4">Meios de contato</h2>
                <div id="contactNumbers">
                    <div id="contact-number-0">
                        <div class="row">
                            <div class="col-12">
                                <select asp-for="Contatos[0].Tipo" class="form-select my-2" aria-label="Selecionar...">
                                    <option value="Residencial" selected>Residencial</option>
                                    <option value="Comercial">Comercial</option>
                                    <option value="Celular">Celular</option>
                                </select>
                            </div>
                        </div>
                        <div class="row mt-2 mb-2">
                            <div class="col-3">
                                <input asp-for="Contatos[0].DDD" type="text" class="form-control dddInput" placeholder="DDD" />
                            </div>
                            <div class="col-9">
                                <input asp-for="Contatos[0].Telefone" type="text" class="form-control phoneInput" placeholder="Número" />
                            </div>
                        </div>
                    </div>
                </div>
                <button type="button" onclick="addContactNumber()" class="btn btn-primary mt-2">+ Novo número</button>
            </div>


            <div class="w-100 form-group border p-4 bg-light">
                <h2 class="h4 w-100">Endereços</h2>
                <div id="contactAddress">
                    <div id="contact-address-0" class="d-flex flex-row flex-wrap gap-5">
                        <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                            <select asp-for="Enderecos[0].Tipo" class="form-select m-2" aria-label="Selecionar...">
                                <option value="Preferencial" selected>Preferencial</option>
                                <option value="Entrega">Entrega</option>
                                <option value="Cobrança">Cobrança</option>
                            </select>
                            <input asp-for="Enderecos[0].Estado" class="form-control m-2" placeholder="Estado" />
                            <span asp-validation-for="Enderecos[0].CEP" class="text-danger"></span>
                            <input asp-for="Enderecos[0].CEP" class="form-control cepInputs m-2" placeholder="CEP (obrigátório)" />
                            <input asp-for="Enderecos[0].Cidade" class="form-control m-2" placeholder="Cidade" />
                            
                        </div>
                        <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                            <input asp-for="Enderecos[0].Bairro" class="form-control m-2" placeholder="Bairro" />
                            <input asp-for="Enderecos[0].Logradouro" class="form-control m-2" placeholder="Rua" />
                            <input asp-for="Enderecos[0].Numero" type="text" class="form-control numberAddressInput m-2" placeholder="Número" />
                            <input asp-for="Enderecos[0].Complemento" class="form-control m-2" placeholder="Complemento" />
                        </div>
                        <div class="w-100 d-flex flex-column align-items-center" style="max-width: 380px;">
                            <textarea asp-for="Enderecos[0].Referencia" class="form-control m-2" placeholder="Referência"></textarea>
                        </div>
                    </div>
                </div>
                <button type="button" onclick="addContactAddress()" class="btn btn-primary mt-3">+ Novo Endereço</button>
            </div>

            <div class="w-100 mb-5">
                <a role="button" class="btn btn-secondary m-1" asp-controller="cliente" asp-action="listar">Cancelar</a>
                <button type="submit" class="btn btn-primary m-1" asp-action="criar">Criar cliente</button>
            </div>
        </form>
    </section>
</div>